# Generated by Django 5.0 on 2025-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('major', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
